import Link from 'next/link'
import { ArrowDown, ArrowRight, ShieldCheck } from 'lucide-react'
import { CategoryCard, EmptyState, NetworkVisual, NewsList, SiteHeader } from '@/components/praivox'
import { getPublishedStories } from '@/lib/publicStories'

export default async function HomePage() {
  // Phase 4 — sirf "published" stories yahan aati hain (approve hote hi
  // automatic, koi manual publish step nahi). Home page pe sabse nayi
  // 6 dikhate hain; poori list category page pe hai.
  const stories = await getPublishedStories({ limit: 6 })

  return <div className="min-h-screen overflow-hidden bg-background"><SiteHeader /><main>
    <section className="relative mx-auto flex min-h-[650px] max-w-7xl items-center px-5 py-24 lg:min-h-[700px] lg:px-8"><NetworkVisual /><div className="relative z-10 max-w-3xl"><div className="mb-8 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[.06] px-3 py-1.5 text-[11px] font-medium tracking-[.15em] text-cyan-200"><ShieldCheck className="size-3.5" /> SIGNAL OVER NOISE</div><h1 className="max-w-3xl font-serif text-[clamp(3.5rem,8vw,7.5rem)] leading-[.94] tracking-[-.055em] text-foreground">Stay Ahead of<br /><span className="text-violet-300">What Matters.</span></h1><p className="mt-8 max-w-lg text-base leading-7 text-muted-foreground lg:text-lg">Verified geopolitical and crypto intelligence, curated from multiple sources.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="#geopolitics" className="inline-flex items-center justify-center gap-2 rounded-lg bg-violet-500 px-5 py-3 text-sm font-medium text-white transition hover:bg-violet-400">Explore Geopolitics <ArrowRight className="size-4" /></Link><Link href="#crypto" className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/[.03] px-5 py-3 text-sm font-medium text-foreground transition hover:border-cyan-300/40 hover:bg-white/[.06]">Explore Crypto <ArrowRight className="size-4" /></Link></div></div><div className="absolute bottom-10 left-5 flex items-center gap-2 text-[10px] tracking-[.2em] text-muted-foreground lg:left-8"><ArrowDown className="size-3" /> SCROLL TO DISCOVER</div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-8 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="mb-3 text-[11px] font-semibold tracking-[.2em] text-cyan-200">THE DAILY BRIEF</p><h2 className="font-serif text-4xl tracking-tight text-foreground">Latest Intelligence</h2></div><p className="max-w-xs text-sm leading-6 text-muted-foreground sm:text-right">Fresh stories, carefully verified and curated.</p></div>{stories.length > 0 ? <NewsList stories={stories} /> : <EmptyState />}</section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-8"><p className="mb-3 text-[11px] font-semibold tracking-[.2em] text-cyan-200">FOLLOW THE SIGNAL</p><h2 className="font-serif text-4xl tracking-tight text-foreground">Explore the coverage</h2></div><div className="grid gap-5 md:grid-cols-2"><CategoryCard type="geopolitics" /><CategoryCard type="crypto" /></div></section>
  </main><footer className="mx-auto flex max-w-7xl flex-col gap-8 border-t border-white/[.08] px-5 py-10 lg:flex-row lg:items-end lg:justify-between lg:px-8"><div><div className="text-sm font-semibold tracking-[.25em] text-foreground">PRAIVOX</div><p className="mt-2 text-xs text-muted-foreground">A New Standard in Digital Engineering</p></div><div className="flex flex-wrap gap-x-6 gap-y-2 text-xs text-muted-foreground"><Link href="/">Home</Link><Link href="/category/geopolitics">Geopolitics</Link><Link href="/category/crypto">Crypto</Link><Link href="/admin/login">Admin Login</Link></div><p className="text-xs text-muted-foreground">© 2026 Praivox. All rights reserved.</p></footer></div>
}
